// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetMessages():Promise<Array<main.Message>>;

export function SendMessage(arg1:string):Promise<string>;
